name: phpMyAdmin
version: 2.0.2
slug: phpmyadmin
description: A web interface for the official MariaDB app
url: https://github.com/erik73/addon-phpmyadmin/
ingress: true
ingress_stream: true
panel_icon: mdi:database
arch:
- aarch64
- amd64
init: false
services:
- mysql:need
hassio_api: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  upload_limit: int?
image: ghcr.io/erik73/phpmyadmin/{arch}
